version: '3.2'
services:
  initial:
    container_name: initial
    image: bazel/services/initial:image
    ports: 
    - "8080:8080"

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_HOST: '${PG_HOST}'
      POSTGRES_PORT: '${PG_PORT}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_DB: '${PG_DB}'
    ports:
    - "${PG_PORT}:${PG_PORT}"
    volumes:
    - ${shell pwd}/database:/database
    - $(shell pwd)/database/postgres:/var/lib/postgresql/data